### PR TITLE
Refactor the Decorator fetch to support multiple calls. See #54

### PR DESCRIPTION
**Pull request by MadsNielsen**

### CODE REVIEW

**Comment by buep** [comment]
Why this pull request? Issue #54 is not in scope and prioritized, so why work on it?

**Comment by buep** [comment]
bue.petersen [16:51]  
why are the suddenly progress on some PAC issues ? But not the one that are either groomed, nor prioritized. This is not how we work.

[16:51]  
feel like I keep repeating myself

jankrag [17:21]  
Because it was Friday afternoon and we got stuck at the whiteboard discussing this feature yet again driven by a possible customer request from @bicschneider .

[17:22]  
After some talk, we decided to sit down all 4 and try some Mob programming.

[17:23]  
So we created a branch and hacked on this for 40 minutes instead of drinking beer.

[17:25]  
Exploratory coding. Not merged. Yes, we could have created a new issue for the part we tackled, but decided to create this issue as a PR instead.

[17:26]  
It is still a issue and thus discussable.

bue.petersen [17:32]  
Okay, you could maybe have supplied that in the comment to the PR? I just saw a PR which usually are supposed to go into the project.

[17:32]  
Shall the PR be declined then or what are your plans?

[17:34]  
And then #58 was also put in progress (by label), but no comment not nothing and that was not even groomed... which makes no sense putting it in progress.

[17:37]  
But PR referenced #54 ... so maybe it was a mistake. Anyway fine you code what-ever but let me in on the details so I don't waste my time looking at something that isn't really relevant.

**Comment by JKrag** [comment]
@buep I don't understand why this PR was closed. I see now that the branch name was incorrect. It should have been called 54-something instead. Is that the only reason you closed it?

As mentioned above, this PR is not a "merge request". It is just a "sub-issue" to #54 created via PR mechanism because the code was already written. We (Mads) will merge ourselves when we are done.
For now it is work in progress. As a minimum, the slightly changed config file format must be documented as well - we are aware of this.

If you want, we (@MadsNielsen ?) could obviously rename the branch, re-push and open a new PR so we don't confuse Waffle.

**Comment by buep** [comment]
You can work from #54 instead if it relates to that, or create a new issue and link to #54.

I closed it because we follow our Pragmatic Workflow and work on issues, and not PR and because it was messy mentioning the wrong branch.

You will not merge it in before we agree on the solution, so work on issues instead.

**Pull request closed without merging**
